import img from '../images/pic.jpg'

export const Data = [
    {
        title : "Data Structures",
        content1 : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. ",
        content2 : "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe voluptatem modi excepturi odio, minus exercitationem beatae impedit id fugiat eum magni officiis! Itaque veniam natus consectetur nisi. Animi, illo dolor. ",
        image : {img}
    }
];