export const Outline = [
    { link : "data-structure", topic : "Data Structure"},
    { link : "array", topic : "Array"},
    { link : "1d-array", topic : "1D Array"},
    { link : "2d-array", topic : "2D Array"},
    { link : "linkedlist", topic : "Linked List"},
    { link : "singly-linkedlist", topic : "Singly Linked List"},
    { link : "doubly-linkedlist", topic : "Doubly Linked List"},
    { link : "circular-singly-linkedlist", topic : "Circular Singly Linked List"},
    { link : "circular-doubly-linkedlist", topic : "Circular Doubly Linked List"},
    { link : "queue", topic : "Queue"},
    { link : "priority-queue", topic : "Priority Queue"},
    { link : "stack", topic : "Stack"},
    { link : "time-complexity", topic : "Time Complexity"},
    { link : "space-complexity", topic : "Space Complexity"},
    { link : "recursion", topic : "Recursion"},
    { link : "trees", topic : "Trees"},
    { link : "binary-tree", topic : "Binary Tree"},
    { link : "binary-search-tree", topic : "Binary Search Tree"},
    { link : "avl-tree", topic : "AVL Tree"},
    { link : "max-heap", topic : "Max Heap"},
    { link : "min-heap", topic : "Min Heap"},
    { link : "pre-order", topic : "Pre Order"},
    { link : "in-order", topic : "In Order"},
    { link : "post-order", topic : "Post Order"},
    { link : "sorting", topic : "Sorting"},
    { link : "bubble-sort", topic : "Bubble Sort"},
    { link : "merge-sort", topic : "Merge Sort"},
    { link : "quick-sort", topic : "Quick Sort"},
    { link : "selection-sort", topic : "Selection Sort"},
    { link : "insertion-sort", topic : "Insertion Sort"},
    { link : "hashing", topic : "Hashing"},
    { link : "hash-tables", topic : "Hash Tables"},
    { link : "graph", topic : "Graph"},
    { link : "dfs", topic : "DFS"},
    { link : "bfs", topic : "BFS"}
];